---
- name: Gather OS information
  shell: |
    if [ -f /etc/os-release ]; then
      cat /etc/os-release | grep "PRETTY_NAME" | cut -d '"' -f2
    else
      echo "-"
    fi
  register: os_info
  changed_when: false
  ignore_errors: true

- name: Gather Nginx version
  shell: |
    if command -v nginx &>/dev/null; then
      nginx -v 2>&1 | awk -F'/' '{print $2}'
    else
      echo "-"
    fi
  register: nginx_version
  changed_when: false
  ignore_errors: true

- name: Gather Consul version
  shell: |
    if command -v consul &>/dev/null; then
      consul --version | head -n1 | awk '{print $2}'
    else
      echo "-"
    fi
  register: consul_version
  changed_when: false
  ignore_errors: true

- name: Gather Nomad version
  shell: |
    if command -v nomad &>/dev/null; then
      nomad --version | head -n1 | awk '{print $2}'
    else
      echo "-"
    fi
  register: nomad_version
  changed_when: false
  ignore_errors: true

- name: Gather Vault version
  shell: |
    if command -v vault &>/dev/null; then
      vault --version | head -n1 | awk '{print $2}'
    else
      echo "-"
    fi
  register: vault_version
  changed_when: false
  ignore_errors: true

- name: Gather Docker version
  shell: |
    if command -v docker &>/dev/null; then
      docker --version | awk '{print $3}' | sed 's/,//'
    else
      echo "-"
    fi
  register: docker_version
  changed_when: false
  ignore_errors: true

- name: Gather Kafka version
  shell: |
    if [ -f /opt/kafka/bin/kafka-topics.sh ]; then
      /opt/kafka/bin/kafka-topics.sh --version | awk '{print $1}'
    else
      echo "-"
    fi
  register: kafka_version
  changed_when: false
  ignore_errors: true

- name: Gather Redis version
  shell: |
    if command -v redis-server &>/dev/null; then
      redis-server --version | awk '{print $3}' | cut -d '=' -f2
    else
      echo "-"
    fi
  register: redis_version
  changed_when: false
  ignore_errors: true

- name: Gather ELK version
  shell: |
    if command -v yum &>/dev/null && yum list installed elasticsearch &>/dev/null; then
      yum info elasticsearch | grep Version | awk '{print $3}' | head -n1
    else
      echo "-"
    fi
  register: elk_version
  changed_when: false
  ignore_errors: true

- name: Gather ClickHouse version
  shell: |
    if command -v clickhouse-server &>/dev/null; then
      clickhouse-server --version | awk '{print $4}' | sed 's/\.$//'
    else
      echo "-"
    fi
  register: ch_version
  changed_when: false
  ignore_errors: true

- name: Gather Scylla version
  shell: |
    if command -v scylla &>/dev/null; then
      scylla --version | awk '{print $1}' | cut -d'-' -f1
    else
      echo "-"
    fi
  register: scylla_version
  changed_when: false
  ignore_errors: true

- name: Gather PHP version
  shell: |
    if command -v php &>/dev/null; then
      php --version | head -n1 | awk '{print $2}'
    else
      echo "-"
    fi
  register: php_version
  changed_when: false
  ignore_errors: true

- name: Collect unreachable hosts
  run_once: true
  delegate_to: localhost
  vars:
    unreachable_hosts: "{{ groups['all'] | difference(ansible_play_hosts) }}"
  set_fact:
    unreachable_hosts: "{{ unreachable_hosts }}"
  ignore_errors: true
